### ISSUE TITLE
Allow  JPG/JPEG compression ?

### ISSUE THREAD

**Issue by vieira83** [excaliburhan/multi-tinypng#2]
The description says it compresses jpg as well. 

> Compress PNG/JPG with TinyPNG API in  terminal

but i don't see the option for jpg/jpeg
below is a PR to allow jpg/JPEG compression
https://github.com/excaliburhan/multi-tinypng/pull/3

**Comment by vieira83** [comment]
https://github.com/excaliburhan/multi-tinypng/pull/3

**Comment by excaliburhan** [comment]
use `tinypng -n xxx.jpg` to compress your jpg/jpeg files.
use `tinypng -h` for more details.

**Comment by excaliburhan** [comment]
I will close this pr as it already support to compress jpg files.
Thanks anyway.
